name: CI for Quote of the Day API

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository locally
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
 
    - name: Install dependencies
      run: npm ci
    
    - name: Fix Linting Issues
      run: npm run lint

    - name: Run tests
      run: npm test
